title: OPP4T
email: maciejmusielik@gmail.com
description: >-
  Program do speedrunowania zadań zamkniętych z matematyki. *może ulec zmianie
baseurl: "/OPP4T/"
url: "https://cheryx.github.io"
github_username: cheryx

theme: minima