title: OPP4T
email: maciejmusielik@gmail.com
description: >-
  Program do speedrunowania zadań zamkniętych z matematyki. *może ulec zmianie
baseurl: "/opp4t"
url: "https://mmusielik.xyz"
github_username: cheryx

theme: minima